config/routes.rb
Fbc::Application.routes.draw do

  get "/session/new" => "sessions#new", as: "new_session"
  post "/session" => "sessions#create", as: "session"
  delete "/session" => "sessions#destroy"

  root "users#index"
  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by username: params[:username]
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "User signed in successfully"
      redirect_to root_url
    else
      flash.now[:error] = "Something went wrong, please try again"
      render 'new'
    end
  end

  def destroy
    reset_session
    flash[:error] = "User signed out"
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
require 'open-uri'

class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user_must_be_user, only: [:show, :edit, :update, :destroy]

  def current_user_must_be_user
    unless current_user == @user
      redirect_to :back, notice: "You are not authorized for that"
    end
  end

  def index
    @users = User.all
  end

  def show
        begin
        url = "https://graph.facebook.com/me/home?access_token=#{@user.facebook_access_token}&limit=200"
        raw_response = open(url).read
        parsed_response = JSON.parse(raw_response)
        @posts = parsed_response['data'].select { |p| p['type'] == 'video' }
      rescue
        flash[:error] = "You must re-authorize facebook"
        @posts = []
      end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
    if @user.save
      format.html { redirect_to @user, notice: "User Successfully Created"}
      format.json { render action: 'show', status: :created, location: @user }
    else
      format.html { render action: 'new' }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    respond_to do |format|
    if @user.update(user_params)
      format.html { redirect_to @user, notice: "User was successfully updated." }
      format.json { head no_content }
    else
      format.html { render action: 'edit' }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation, :facebook_access_token, :facebook_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Fbc</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>


  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Fbc</a>
        <div class="nav-collapse">
          <ul class="nav">
              <% if current_user.present? %>
              Hello <%= link_to current_user.username, current_user %>
            <li><%= link_to "Sign Out", session_url, method: 'delete' %></li>
            <% else %>
            <li><%= link_to "Sign In", new_session_url %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>
  <% msg %>
  <% end %>
  <% end %>

<%= form_for @user do |f| %>
  <div>
  <%= f.label :username %>
  <%= f.text_field :username %>
  </div>
   <div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  </div>
   <div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  </div>
   <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>
   <div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </div>
   <div>
  <%= f.label :facebook_access_token %>
  <%= f.text_field :facebook_access_token %>
  </div>
   <div>
  <%= f.label :facebook_id %>
  <%= f.text_field :facebook_id %>
  </div>
  <%= f.submit "Action" %>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>

  <%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Password digest</th>
      <th>Facebook access token</th>
      <th>Facebook</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.password_digest %></td>
      <td><%= user.facebook_access_token %></td>
      <td><%= user.facebook_id %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


  <%= render 'form' %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Facebook access token:</b>
  <%= @user.facebook_access_token %>
</p>

<p>
  <b>Facebook:</b>
  <%= @user.facebook_id %>
</p>

<% @posts.each do |post| %>
  <ul class="media-list">
    <li class="media">
      <div class="pull-left">
        <%= image_tag "https://graph.facebook.com/#{post['from']['id']}/picture" %>
      </div>
      <div class="media-body">
        <h2 class="media-heading">
        <%= post['from']['name'] %>
        </h2>
        <p class="lead"><%= post['message'] %></p>
        <%= link_to 'Click To Watch', post['link'], target: '_blank' %>

      </li>
  </ul>
   </div>
  <% end %>